### ISSUE TITLE
localStorage.requirements does not have date for the requirements

### ISSUE THREAD

**Issue by RyanLoringCooper** [COEN174/MainProject#53]
A class will stay white when it is scheduled because localStorage.requirements does not have a place for date in each class. 
I also do not know if there is code to make them yellow if they are scheduled.

**Comment by RyanLoringCooper** [comment]
Oh I meant to say this is on the moreReqs branch.

**Comment by RyanLoringCooper** [comment]
It also sometimes does not put in a json entry in localStorage (it does this for Social_Science).

**Comment by jkingsman** [comment]
Is this also fixed by whatever fixed #54? I haven't checked out your branch yet but localStorage should be storing that correctly (and is on master).

**Comment by RyanLoringCooper** [comment]
No. The fix for #54 made it so that when you hit enter with a valid class in the text area, then all the classes turn yellow. date is still not in localStorage.requirements

**Comment by RyanLoringCooper** [comment]
It does work in master though so I did do something that broke it. I will investigate.

**Comment by jkingsman** [comment]
Perfect; was just about to say Master seems to be alright with that -- 
![image](https://cloud.githubusercontent.com/assets/2365891/20150731/3449ed44-a66c-11e6-883c-56168d93f981.png)

I'm gonna assign this to you; feel free to kick it back to me if you can't figure out the glitch

**Comment by RyanLoringCooper** [comment]
Is master's ui driven by localStorage?

**Comment by jkingsman** [comment]
I'm a way - display is from the data but any changes are made to the UI then reflected by the data driven by jQuery. I think we can keep both methods and use the appropriate one to display data in the UI or save UI to data when we need. 

Sent from a tiny screen; forgive brevity or typos, please.

Jack W. Kingsman
Full Stack Development & Devops
415.895.2887
http://jacksbrain.com/
https://github.com/jkingsman/

**Comment by jkingsman** [comment]
I believe this is working fine now; I'm going to go ahead and close.
